### ISSUE TITLE
mistake in readme

### ISSUE THREAD

**Issue by stavinsky** [prateeknischal/fzf-pass#2]
echo "export PASSWORD_STORE_ENABLE_EXTENSIONS=yes" >> ~/.bash_profile 

PASSWORD_STORE_ENABLE_EXTENSIONS should be true, not yes. 
from man page:
"This environment variable must be set to "true" for extensions to be enabled."

**Comment by prateeknischal** [comment]
Thanks for the catch @stavinsky. I have updated the README in [`4a1e31f`](https://github.com/prateeknischal/fzf-pass/commit/4a1e31f0e58cf051b42ba5e2b7c0e871ac9e50ee)
